--SELECT * 
--FROM 
--INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--,INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
--WHERE INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME	= INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.COLUMN_NAME
----AND INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME			= INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME
----AND INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE = N'PRIMARY KEY'
----AND 
----INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME	= N'Directors';

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE = N'PRIMARY KEY'
AND INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME	= N'Directors';